<?php include 'includes/header.php' ?>
		  <div class="blog-post">
            <h2 class="blog-post-title">International PHP Conference 2015</h2>
            <p class="blog-post-meta">January 1, 2015 by <a href="#">Mark</a></p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sagittis nisl sed ex tempor, vitae vestibulum sem egestas. Mauris et eros consequat neque cursus pretium in nec justo. Donec suscipit magna eget mi egestas aliquam. Duis at cursus justo, et tincidunt tortor. Fusce id purus quis turpis placerat interdum. Ut semper tortor et vulputate pulvinar. Mauris posuere eu erat id mollis. Suspendisse elementum enim iaculis congue facilisis. Mauris urna velit, sagittis non tortor at, aliquam elementum orci. Nulla eget quam eu nibh tristique fringilla in vitae dui. Proin aliquam viverra est nec maximus. Morbi quis tortor congue libero pellentesque pulvinar vitae id nibh. Curabitur imperdiet odio ut sem aliquam iaculis. Donec dolor sapien, vehicula sed dui ut, fermentum vehicula ipsum. Aliquam eget mi nulla. Fusce luctus mollis urna, id molestie arcu dictum vitae. Proin placerat, nulla quis commodo facilisis, purus urna lobortis purus, ac varius velit risus eu tellus. Donec tempus arcu sem, mattis pharetra felis tempor nec. Suspendisse bibendum, ligula id pulvinar ornare, lectus quam sagittis mi, in porttitor sem justo sit amet ante.</p>
				<p>Morbi accumsan, magna sed rutrum varius, quam nibh lacinia leo, sit amet dignissim sapien massa in turpis. Sed vitae turpis laoreet elit facilisis laoreet. Aenean nec felis nec diam maximus iaculis. Donec ac neque in lectus sodales dapibus et eget turpis. Curabitur at bibendum turpis, ut feugiat tortor. In non ex laoreet ex malesuada ornare sed sit amet ante. Donec vitae purus hendrerit augue viverra tincidunt nec quis nunc. Fusce sit amet tincidunt orci. Nullam sollicitudin ullamcorper nunc ac dapibus. Etiam diam ligula, rhoncus at nisl eu, imperdiet malesuada nisi. Donec id neque ac nulla luctus posuere. Integer venenatis tellus in erat dignissim luctus. Sed nec congue justo, sed sollicitudin ipsum. Nulla mollis nisi vitae accumsan tristique. Vestibulum dictum at tellus vel mattis.</p>
				<p>Curabitur placerat libero ac augue tempus, non dignissim ipsum vulputate. Suspendisse at eros nec magna elementum tempor quis non dui. Quisque id diam consectetur, pretium diam ut, pellentesque lectus. Curabitur gravida sollicitudin urna ac sodales. Nulla est elit, viverra et turpis in, fringilla feugiat nisi. Phasellus sit amet dolor at nibh pretium lacinia. Morbi vestibulum varius cursus. Duis mi lectus, vehicula at varius non, sollicitudin eget ante. Pellentesque risus risus, feugiat in nisl ac, malesuada dignissim massa. Suspendisse eu hendrerit nunc, eget ornare leo. Pellentesque in mi nec nisi fermentum tempor ac sed diam. Duis rhoncus nisi cursus, finibus tortor quis, laoreet nunc. Vestibulum sed mollis massa.</p>
          </div><!-- /.blog-post -->
<?php include 'includes/footer.php' ?>
